name: Flutter CI

on: [push, pull_request]

jobs:
  unit-tests:
    name: Run Unit Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Flutter
        uses: subosito/flutter-action@v2

      - name: Install dependencies
        run: flutter pub get

      - name: Run unit tests
        run: flutter test

  # integration-tests:
  #   name: Run Integration Tests
  #   needs: unit-tests
  #   runs-on: ubuntu-latest

  #   steps:
  #     - uses: actions/checkout@v2

  #     - name: Setup Flutter
  #       uses: subosito/flutter-action@v2

  #     - name: Install dependencies
  #       run: flutter pub get

  #     - name: Set up JDK 11
  #       uses: actions/setup-java@v2
  #       with:
  #         java-version: '11'
  #         distribution: 'adopt'

  #     - name: Start Android Emulator
  #       uses: reactivecircus/android-emulator-runner@v2
  #       with:
  #         api-level: 29
  #         arch: x86
  #         profile: pixel
  #         script: flutter test integration_test
